name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/haskell.yml
  release:
  steps:
  - name: Release
    run: |
     echo "Atlas version: $ATLAS_VERSION"
     # export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
     # gh release create \
     #   --generate-notes \
     #   --verify-tag \
     #   'v1.0.0' \
     #   './generated_docs/index.html#documentation'
