name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/haskell.yml
  release:
    runs-on: ubuntu-22.04
    steps:
    - name: Release    
      run: |
       echo "Atlas version: $ATLAS_VERSION"
