name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/haskell.yml
  release:
    runs-on: ubuntu-22.04
    needs: build
    steps:
    - name: Release    
      env:
        ATLAS_VERSION: ${{needs.build.outputs.build}}
      run: echo "${{ env.ATLAS_VERSION }"
